# Site wide configuration
title: Kundan Kumar
locale: en_US
url: "https://kundan-kumarr.github.io"

# Jekyll configuration
# permalink: /:categories/:title/
permalink: /posts/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Analytics
analytics:
  provider: "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id: ""

# Pagination
pagination:
  enabled: true

related_blog_posts:
  enabled: true
  max_related: 5

# Site owner
owner:
  name: Kundan Kumar
  avatar: bio.jpg
  position: Ph.D. Candidate
  school: Iowa State University
  place: Ames, Iowa, US
  bio: "I am a PhD Candidate in Computer Science with a minor in Statistics at Iowa State University. My areas of interest include Reinforcement Learning, Machine Vision, and AI-Security."
  email: kkumar@iastate.edu
  disqus-shortname: kundan

  twitter: kundan7kumar #username
  facebook: #username
  # google:
  #   plus: ""
  #   analytics: ""
  #   verify: ""
  #   ad-client: ""
  #   ad-slot: ""
  # bing-verify: ""
  googlescholar: "1zDpIJkAAAAJ"
  github: "kundan-kumarr"
  linkedin: "kundan-kumarr" #username
  medium: "https://kkresearch.medium.com/"
  youtube: "@AIAgentic-007"
  orcid: "0000-0002-3229-6649"
  # instagram: ""
  # lastfm: ""
  # tumblr: ""
  # pinterest: ""
  # foursquare: ""
  # steam: ""
  # dribbble: ""
  # stackoverflow: #123456/username   # from a "http://stackoverflow.com/users/123456/username" link
  # soundcloud: ""
  # weibo: ""
  # flickr: ""
  # codepen: ""
  # scholar: ""
  # medium: @kkundannqs

# Navigation
# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults for collections
defaults:
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true

# Sidebar navigation
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "notes"
      
# Navigation

include:
  - ".htaccess"
  - "_pages"
  - "files"
exclude:
  - "lib"
  - "config.rb"
  - "Capfile"
  - "config"
  - "log"
  - "Rakefile"
  - "Rakefile.rb"
  - "tmp"
  - "less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "test"
  - "spec"
  - "Gruntfile.js"
  - "package.json"
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
