---
title: "Deep RL-based volt-var control and attack resiliency for der-integrated distribution grids"
type: "article"
author: "Kundan Kumar"
date: "2024-02-19"
year: "2024"
publication: "IEEE Power & Energy Society Innovative Smart Grid Technologies Conference (ISGT)"
doi: "10.1109/ISGT59692.2024.10454163"
toc: false
categories:
  - Reinforcement Learning
  - Secure AI
  - Smart Energy Systems
thumbnail: "/misc/info/pubs/thumbs/isgt.png"
---
<div style="display:flex; justify-content:flex-end; margin-top:-0.5rem; gap:0.5rem;">
  <a class="btn btn-primary" href="/misc/info/posters/PES_ISGT_poster.pdf" target="_blank" rel="noopener"> Poster (PDF)
  </a>
</div>

## Citation

> K. Kumar and G. Ravikumar, "Deep RL-based Volt-VAR Control and Attack Resiliency for DER-integrated Distribution Grids," 2024 IEEE Power & Energy Society Innovative Smart Grid Technologies Conference (ISGT), Washington, DC, USA, 2024, pp. 1-5, doi: 10.1109/ISGT59692.2024.10454163.

## Abstract

Integrating distributed energy resources (DERs) into a power system requires more advanced control mechanisms. One of the control strategies used for Volt-VAR control (VVC) is to manage voltage and reactive power. With the increase in the complexity of the power system, there is a need to develop an autonomous and robust control mechanism using deep reinforcement learning (DRL) to enhance grid performance and adjust voltage and reactive power settings. These adjustments minimize losses and enhance voltage stability in the grid. In this paper, we proposed a novel approach to develop a DRL-based VVC framework and mitigation techniques to protect against stealthy white-box attacks targeting the trained control policies of the DRL model. The mitigation technique on the trained DRL is proposed to control the voltage violations on the smart grid to enhance the stability of the grid and minimize voltage irregularities. Our proposed mitigation technique provided better control policies for DRL-based VVC, successfully mitigating 100 percent of voltage violations in the smart grid environment. The results show that the mitigation technique enhances the security and robustness of trained DRL VVC agents.
