---
title: "Bayesian-Optimized Bidirectional Long-Short-Term Memory network for Wind Power Forecasting with Uncertainty Quantification"
type: "article"
author: "Kundan Kumar"
year: "2025"
publication: "Electric Power Systems Research (under Review)"
preprint: ""
doi: ""
materials: ""
toc: false
categories:
  - Uncertainty Esitmation
  - Time Series Analysis
  - Forecasting
---

## Citation 

> 

## Abstract

#### Objective

Wind energy technologies, including advanced \textcolor{blue}{turbine} management and scheduling, rely on accurate wind power
forecasting (WPF) for optimal operation. Enhancing forecast
precision is crucial for reducing volatility in wind power
\textcolor{blue}{integration} and improving forecasting reliability. While \textcolor{blue}{time series} forecasting methods estimate future values from historical
data, traditional approaches often struggle with computational
efficiency and model complexity. To address these challenges,
we propose a hybrid forecasting model that integrates multi-
variate estimation (MVE) and pure  \textcolor{blue}{time series} prediction (TSP)
using a bidirectional long-short-term memory network (Bi-
LSTM) optimized with Tree-structured Parzen Estimator (TPE)-
based Bayesian optimization. The model incorporates numerical
weather prediction (NWP) data for real-time forecasting, \textcolor{blue}{addressing} a key limitation in existing methods. MVE utilizes \textcolor{blue}{meteorological} features such as wind speed, direction, temperature,
and pressure, while TSP captures historical power generation
patterns. The TPE-optimized Bi-LSTM architecture effectively
captures bidirectional temporal dependencies, improving \textcolor{blue}{accuracy} in both short-term and long-term forecasting. The model is
evaluated using a six-year historical wind energy dataset from
NREL, with performance assessed through RMSE, MAE, and R2
score. It outperforms traditional LSTM variants (Vanilla LSTM,
Stacked LSTM, Bi-LSTM) and state-of-the-art models such as
Transformers and GRUs, achieving R² scores of 0.976 for MVE
and 0.932, 0.928, and 0.864 for TSP across short-term, day-
ahead, and long-term forecasting, respectively. Additionally, TPE based Bayesian optimization reduces computational time around
8-10\%, enhancing hyperparameter tuning efficiency. The study
further analyzes the model’s computational burden, scalability,
and practical implementation, offering a robust and efficient
approach for improving wind power forecasting accuracy. \textcolor{blue}{While the model achieves high accuracy on the NREL dataset, future work will validate its performance across diverse geographic regions (e.g., Europe, Asia) and turbine configurations}

#### Method
 ($N_{ASD}=23$, $N_{NT}=52$) 

#### Results


#### Conclusions


