---
title: "A Multi-Objective Optimization Framework for Carbon-Aware Smart Energy Management"
type: "article"
pubtype: conference 
author: "Kundan Kumar"
date: "2025-10-29"
publication: "57th IEEE North American Power Symposium (NAPS)"
doi: "10.1109/NAPS66256.2025.11272265"
toc: false
categories:
  - Machine Learning
  - Multi-Objective Optimization
  - Energy Optimization
thumbnail: "/misc/info/pubs/thumbs/naps.gif"
---
<div style="display:flex; justify-content:flex-end; margin-top:-0.5rem; gap:0.5rem;">
  <a class="btn btn-primary" href="/misc/info/presentations/Multi_objective_NAPS_presentation.pdf" target="_blank" rel="noopener"> Presentation (PDF)
  </a>
</div>

## Citation

> K. Kumar and G. Ravikumar, "A Multi-Objective Framework for Energy, Cost, and Carbon Trade-offs in Smart Energy Systems," 2025 57th North American Power Symposium (NAPS), Storrs, CT, USA, 2025, pp. 1-6, doi: 10.1109/NAPS66256.2025.11272265.

## Abstract
As renewable energy sources become more integrated into the power grid, efficient scheduling of household energy consumption is essential to reduce costs and carbon footprint. In this paper, we introduce an energy optimization framework that optimizes the timing of appliance use based on dynamic carbon intensity and electricity prices. We determine optimal operation schedules using a multi-objective optimization model with a Gurobi solver and machine learning. We combine Random Forest and XGBoost for demand prediction, incorporating their uncertainty estimates into the optimization constraints. The model optimizes ON/OFF appliance schedules while considering constraints like minimum operating times and power balance. It shifts usage to lower-cost and carbon-intensity periods, which helps to reduce energy consumption.

Key contributions include ML-based demand predictions and mixed-integer programming (MIP) optimization that improves robustness to prediction errors while adjusting schedules based on time-of-use pricing and carbon intensity. Our smart scheduling and load shifting achieve a 35.8% reduction in costs, a
38.6% decrease in carbon emissions, and a 25.8% reduction in peak demand using a carbon-aware scheduling algorithm. This framework effectively shifts loads to low-cost, low-carbon times, offering significant economic and environmental benefits for residential energy management without compromising user comfort.

## Impact Statement


