---
title: "Bayesian Optimization for Deep Reinforcement Learning for Robust Volt-Var Control"
type: "article"
author: "Kundan Kumar"
date: 2024-01-01
year: "2024"
publication: "IEEE"
doi: "10.1109/PESGM51994.2024.10688889"
toc: false
categories:
  - Bayesian Optimization
  - Reinforcement Learning
  - Smart Energy Systems
---
<div style="display:flex; justify-content:flex-end; margin-top:-0.5rem; gap:0.5rem;">
  <a class="btn btn-primary" href="/misc/info/posters/Bayesian_PESGM_poster.pdf" target="_blank" rel="noopener"> Poster (PDF)
  </a>
</div>

## Citation

> K. Kumar, A. A. Mantha and G. Ravikumar, "Bayesian Optimization for Deep Reinforcement Learning for Robust Volt-Var Control," 2024 IEEE Power & Energy Society General Meeting (PESGM), Seattle, WA, USA, 2024, pp. 1-5, doi: 10.1109/PESGM51994.2024.10688889.

## Abstract

The high penetration of Renewable Energy Sources (RES) into the grid introduces complexity to the operation and optimization of energy. One potential solution to the challenge is to use deep reinforcement learning (DRL) based techniques to regulate voltage and reactive power under dynamic conditions. However, there is a need to optimize the DRL for better performance and robustness. This paper proposes a Bayesian optimization (BO) technique within the DRL framework to improve the performance and robustness of volt-var control (VVC) in power distribution systems. We combine the actor-critic DRL algorithm with the BO framework to yield fast optimal volt-var control policies. We use BO techniques to estimate DRL-based VVC decisions and accelerate model-training convergence. In the case study, we demonstrated that the BO in DRL on IEEE-13 has improved decision-making by 21.11% and 81.81% for 123 bus test systems. Our research shows that Bayesian-enabled DRL adapts to different grid configurations and maintains voltage profiles within desired limits, thereby improving DRL control policies.
